#!/usr/bin/env bash
# ======================================================================
#  PiStock — one-shot installer for Raspberry Pi (Raspberry Pi OS /
#  Debian-based). Run it from inside the cloned repository, as your
#  NORMAL user (it calls sudo only when needed):
#
#      git clone <repo-url> pistock
#      cd pistock
#      ./deploy/install_pi.sh
#
#  What it does:
#    1. installs system packages (python3-venv, git, openssl);
#    2. creates a Python virtualenv (.venv) and installs requirements;
#    3. initializes the database (../data-pistock) if absent;
#    4. writes pistock.conf with the detected LAN IP;
#    5. generates a self-signed TLS certificate (once);
#    6. installs + enables a systemd service (autostart on every boot);
#    7. prints the LAN IP/URL to configure the FreeCAD macros.
# ======================================================================
set -euo pipefail

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m  ✓ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m  ! %s\033[0m\n' "$*"; }

# --- 0. Sanity: not as root (venv/data must belong to the real user) --
if [ "$(id -u)" -eq 0 ]; then
  echo "Please run this script as your normal user, NOT as root/sudo." >&2
  echo "It will call sudo itself for the steps that need it." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DATA_DIR="$(cd "$(dirname "$REPO_DIR")" && pwd)/data-pistock"   # sibling of repo
RUN_USER="$(id -un)"
PISTOCK_PORT="${PISTOCK_PORT:-8000}"
PISTOCK_DNS="${PISTOCK_DNS:-pistock.local}"
cd "$REPO_DIR"

detect_ip() {
  local ip
  ip="$(ip route get 1.1.1.1 2>/dev/null | sed -n 's/.*src \([0-9.]*\).*/\1/p' | head -n1 || true)"
  [ -z "$ip" ] && ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  echo "${ip:-127.0.0.1}"
}
PI_IP="$(detect_ip)"

say "PiStock installer"
echo "  Repository : $REPO_DIR"
echo "  Data dir   : $DATA_DIR"
echo "  User       : $RUN_USER"
echo "  LAN IP     : $PI_IP   Port: $PISTOCK_PORT"

# --- 1. System packages ----------------------------------------------
say "1/7 Installing system packages (sudo)"
sudo apt-get update -y
sudo apt-get install -y python3 python3-venv git openssl
ok "system packages ready"

# --- 2. Virtualenv + dependencies ------------------------------------
say "2/7 Python virtualenv + dependencies"
if [ ! -d .venv ]; then
  python3 -m venv .venv
  ok "virtualenv created (.venv)"
else
  ok "virtualenv already present (.venv)"
fi
./.venv/bin/pip install --upgrade pip
./.venv/bin/pip install -r requirements.txt
ok "dependencies installed"

# --- 3. Database init (skip if it already exists) --------------------
say "3/7 Database initialization"
if [ -f "$DATA_DIR/pistockdatabase.sqlite3" ]; then
  warn "database already exists at $DATA_DIR — left untouched"
else
  ./.venv/bin/python backend/app/install/init_db.py
  ok "database created at $DATA_DIR"
fi

# --- 4. Configuration file -------------------------------------------
say "4/7 Configuration (pistock.conf)"
if [ -f pistock.conf ]; then
  warn "pistock.conf already exists — left untouched (check it manually)"
else
  cat > pistock.conf <<EOF
# Generated by deploy/install_pi.sh
PISTOCK_DIR="$REPO_DIR"
PISTOCK_IP="$PI_IP"
PISTOCK_DNS="$PISTOCK_DNS"
PISTOCK_PORT="$PISTOCK_PORT"
EOF
  ok "pistock.conf written (IP=$PI_IP, port=$PISTOCK_PORT)"
fi

# --- 5. Self-signed TLS certificate (once) ---------------------------
say "5/7 TLS certificate"
if [ -f key.pem ] && [ -f cert.pem ]; then
  warn "key.pem/cert.pem already present — kept"
else
  # SAN also covers 127.0.0.1 / localhost so local tests on the server
  # itself pass strict certificate verification.
  openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem \
    -days 825 -nodes \
    -subj "/CN=${PI_IP}" \
    -addext "subjectAltName=IP:${PI_IP},DNS:${PISTOCK_DNS},IP:127.0.0.1,DNS:localhost"
  chmod 600 key.pem
  ok "self-signed certificate generated"
fi

# --- 6. systemd service (autostart) ----------------------------------
say "6/7 systemd service (autostart on boot)"
sudo tee /etc/systemd/system/pistock.service > /dev/null <<EOF
[Unit]
Description=PiStock (PLM/inventory server)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$REPO_DIR
# Put the venv first on PATH so startapp.sh's bare 'uvicorn' is the venv one
Environment=PATH=$REPO_DIR/.venv/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=/usr/bin/env bash $REPO_DIR/backend/app/startapp.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl enable pistock >/dev/null 2>&1 || true
sudo systemctl restart pistock
ok "service installed and started"

# --- 7. Readiness check + final summary ------------------------------
say "7/7 Checking the server"
URL="https://${PI_IP}:${PISTOCK_PORT}"
sleep 4
if curl -sk -o /dev/null -w '%{http_code}' "https://127.0.0.1:${PISTOCK_PORT}/login" | grep -q '200'; then
  ok "server is up"
else
  warn "server not answering yet — check: journalctl -u pistock -e"
fi

cat <<EOF

======================================================================
  ✅ PiStock is installed and running.

  Open it in a browser (accept the self-signed certificate warning):
      ${URL}/

  → On FIRST visit you set the ACCESS password (the front door).
    The ADMIN password (for deletions, db_admin plugin) is set
    separately the first time you do a destructive action.

  ----------------------------------------------------------------
  📐 FreeCAD macros — point them to this server:
       On each FreeCAD workstation, copy
         backend/CAD-extensions/freecad/pistock_host.txt.example
       to  pistock_host.txt  and put this single line in it:

           ${PI_IP}

       (the macros will use ${URL})
  ----------------------------------------------------------------

  Manage the service:
      sudo systemctl status pistock
      sudo systemctl restart pistock      # after a 'git pull'
      journalctl -u pistock -f            # live logs
======================================================================
EOF
